version: '3.8'

services:
  poseapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads   # 方便本地保留上傳檔案
      - ./templates:/app/templates  # 挂载 templates 資料夾 (如果你有用本地模板)
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
